name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Parse MD Files
      env:
        JULIET_POST_TOKEN: ${{ secrets.BLOG_POST_TOKEN }}
        RUN_MODE: gh-actions
      run: go run tool/main.go

    - name: Copy Pic Directory
      run: mkdir -p public && cp -r pic public

    - name: Prepare html for gh-page
      run: mv ./tool/index.html ./public/index.html && cp ./public/index.html ./public/404.html && mv ./README.MD ./public/README.MD

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Set Git user.name
        user_name: Lewin Lan
        # Set Git user.email
        user_email: lewin.lan.cn@gmail.com
  
